version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - app

  pma:
    image: phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      PMA_HOST: '${DB_HOST}'
      PMA_PORT: '${DB_PORT}'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.rule=Host(`pma.localhost`)"
      - "traefik.http.routers.phpmyadmin.entrypoints=web"
    depends_on:
      - mysql
    networks:
      - app

  php-dev:
    image: 'webdevops/php-nginx-dev:8.0'
    user: '${UID:-1000}'
    container_name: '${APP_NAME}-php'
    working_dir: /var/www/html
    environment:
      - WEB_DOCUMENT_ROOT=/var/www/html/public
    volumes:
      - './:/var/www/html'
      - '~/.ssh:/home/application/.ssh'
      - '~/.ssh:/root/.ssh'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_NAME}-php.rule=Host(`${APP_NAME}.localhost`)"
      - "traefik.http.routers.${APP_NAME}-php.entrypoints=web"
    networks:
      - app
    depends_on:
      - mysql

  npm-dev:
    container_name: 'npm-dev'
    image: node:18
    working_dir: /var/www/html
    entrypoint: [ "npm" ]
    volumes:
      - './:/var/www/html'

volumes:
  mysql:
    driver: local

networks:
  app:
    driver: bridge
   
