version: '3'
services:
    php-dev:
        build:
            context: ..
            dockerfile: ../Dockerfile
        image: laravel-app
        container_name: '${APP_NAME-app}'
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
            - ./apache2.conf:/etc/apache2/apache2.conf
            - ./default.conf:/etc/apache2/sites-available/000-default.conf
        ports:
            - '8000:8000'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        depends_on:
            - mysql
        networks:
            - app

    mysql:
        image: mysql:8.0
        container_name: mysql
        environment:
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        ports:
            - '3306:3306'
        volumes:
            - mysql:/var/lib/mysql
        networks:
            - app

    pma:
        image: phpmyadmin
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            PMA_HOST: '${DB_HOST}'
            PMA_PORT: '${DB_PORT}'
        ports:
            - '5050:80'
        depends_on:
            - mysql
        networks:
            - app

    npm-dev:
        container_name: 'npm-dev'
        image: node:18
        working_dir: /var/www/html
        entrypoint: [ "npm" ]
        ports:
            - '3000:3000'
            - '3001:3001'
        volumes:
            - './:/var/www/html'

volumes:
    mysql:
        driver: local

networks:
    app:
        driver: bridge
